[theme]
name = "Rosé Pine"
author = "Rosé Pine"
variant = "dark"
version = "1.0.0"
description = "All natural pine, faux fur and a bit of soho vibes for the classy minimalist"

[colors]
foreground = "#e0def4"
background = "#191724"
cursor = "#524f67"
selection_fg = "#e0def4"
selection_bg = "#403d52"
black = "#26233a"
red = "#eb6f92"
green = "#31748f"
yellow = "#f6c177"
blue = "#9ccfd8"
magenta = "#c4a7e7"
cyan = "#ebbcba"
white = "#e0def4"
bright_black = "#6e6a86"
bright_red = "#eb6f92"
bright_green = "#31748f"
bright_yellow = "#f6c177"
bright_blue = "#9ccfd8"
bright_magenta = "#c4a7e7"
bright_cyan = "#ebbcba"
bright_white = "#e0def4"
